fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat'
      ref: '2.1.0'
    vcsrepo:
      repo: 'git://github.com/puppetlabs/puppetlabs-vcsrepo'
    openssl:
      repo: 'git://github.com/camptocamp/puppet-openssl'
  symlinks:
    'letsencrypt': "#{source_dir}"
